### ISSUE TITLE
DarkChannelImage_Create bug

### ISSUE THREAD

**Issue by JinCho23** [terry77228/Image-Dehase#1]
In line 64 of Dehaze.cpp, pixel indices (i,j) should be replaced to (m,n).

**Comment by terry77228** [comment]
Fixed, thanks.

**Comment by JinCho23** [comment]
Thanks for your quick feedback.
DarkVal needs to be compared with itself (previous value), too.
DarkVal = std::min(std::min(std::min(m_Image.at<Vec3b>(m, n)[0], m_Image.at<Vec3b>(m, n)[1]), m_Image.at<Vec3b>(m, n)[2]), DarkVal);
